version: '3'

services:
  traefik:
    image: traefik:alpine
    command: --docker
    ports:
      - '80:80'
      - '443:443'
    labels:
      - 'traefik.frontend.redirect.entryPoints=http'
      - 'traefik.frontend.rule=Host:traefik.mahfoudi.me'
      - 'traefik.port=8080'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './traefik.toml:/traefik.toml'
      - './acme.json:/acme.json'
    networks:
      - 'proxy'
    container_name: traefik
    restart: always

networks:
  proxy:
    external: true
